# Project Luther

For this project, my goal is to predict the total box office gross on the opening week using a linear regression model. This notebook contains all the data scraping to create the dataframes needed. My variables of interest come from three sources: BoxOfficeMojo, Youtube, and  data

Note to self:
#### common columns 
(mojo_df & youtube_df): movie_name
(mojo_df & omdb_df): movie

# Scrape Box Office Data Using BeautifulSoup
I will be scraping the box office data from boxofficemojo

In [4]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import time
import seaborn as sns

In [285]:
# define a function that can scrape top 100 movies of a given year in boxofficemojo.com
# scrape movie name, opening gross, theaters, release date
def get_opening(soup, year):
    table = soup.find_all('table')[4].find_all('tr')[2].find('table')
    movie_list = []
    for row in table.find_all('tr')[2:102]:
        cells = row.find_all('td')
        if len(cells) > 0:
            movie_name = cells[1].text
            tot_gross = cells[3].text
            opening = cells[5].text
            theaters = cells[6].text
            release_date = cells[7].text + "/" + year
            cell_dict = {'movie_name': movie_name, 'tot_gross':tot_gross, 'opening': opening, 'theaters': theaters, 'release_date': release_date}
            movie_list.append(cell_dict)
    return movie_list

In [3]:
# # Test code
# year = '2012'
# url = 'http://www.boxofficemojo.com/yearly/chart/?yr='
# url = url + year + '&sort=opengross'
# response = requests.get(url)
# soup = BeautifulSoup(response.text, 'lxml')
# table = soup.find_all('table')[4].find_all('tr')[2].find('table')
# movie_list = []
# for row in table.find_all('tr')[100:102]:
#     cells = row.find_all('td')
#     if len(cells) > 0:
#         movie_name = cells[1].text
#         opening = cells[5].text
#         theaters = cells[6].text
#         release_date = cells[7].text + "/" + year
#         cell_dict = {'movie_name': movie_name, 'opening': opening, 'theaters': theaters, 'release_date': release_date}
#         movie_list.append(cell_dict)
# movie_list

In [286]:
# Loop over selected years (2013 - 2017) to scrape movie data
years = ['2013','2014','2015','2016','2017']

def scrape_boxoffice(years):
    movie_list = []
    for year in years:
        url = 'http://www.boxofficemojo.com/yearly/chart/?yr='
        url = url + year
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'lxml')
        if len(movie_list) == 0:
            movie_list = get_opening(soup, year)
        else:
            movie_list = movie_list + get_opening(soup, year)
        # pause for 5seconds to limit traffic
        time.sleep(5)
        print("Successfully scraped " + year + "'s list")
    return movie_list
    
movie_list = scrape_boxoffice(years)

Successfully scraped 2013's list
Successfully scraped 2014's list
Successfully scraped 2015's list
Successfully scraped 2016's list
Successfully scraped 2017's list

In [287]:
# Convert the list of dictionaries to a pandas dataframe
mojo_df = pd.DataFrame(movie_list)
mojo_df.head()

,movie_name,opening,release_date,theaters,tot_gross
0,The Hunger Games: Catching Fire,"$158,074,286",11/22/2013,"4,163","$424,668,047"
1,Iron Man 3,"$174,144,585",5/3/2013,"4,253","$409,013,994"
2,Frozen,"$243,390",11/22/2013,1,"$400,738,009"
3,Despicable Me 2,"$83,517,315",7/3/2013,"3,997","$368,061,265"
4,Man of Steel,"$116,619,362",6/14/2013,"4,207","$291,045,518"

In [288]:
# create new column called movie, with the years stripped
# create a new column converting release date to date_time
# convert opening(in dollars) to numeric
movie_strip = mojo_df.movie_name.replace("[(]?\d\d\d\d[)]","", regex = True).str.strip()
date_time = pd.to_datetime(mojo_df.release_date, format="%m/%d/%Y")
mojo_df.insert(loc=1, column='movie', value=movie_strip)
mojo_df.insert(loc=3, column='date_time', value=date_time)
mojo_df.head()

,movie_name,movie,opening,date_time,release_date,theaters,tot_gross
0,The Hunger Games: Catching Fire,The Hunger Games: Catching Fire,"$158,074,286",2013-11-22,11/22/2013,"4,163","$424,668,047"
1,Iron Man 3,Iron Man 3,"$174,144,585",2013-05-03,5/3/2013,"4,253","$409,013,994"
2,Frozen,Frozen,"$243,390",2013-11-22,11/22/2013,1,"$400,738,009"
3,Despicable Me 2,Despicable Me 2,"$83,517,315",2013-07-03,7/3/2013,"3,997","$368,061,265"
4,Man of Steel,Man of Steel,"$116,619,362",2013-06-14,6/14/2013,"4,207","$291,045,518"

In [289]:
mojo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
movie_name      500 non-null object
movie           500 non-null object
opening         500 non-null object
date_time       500 non-null datetime64[ns]
release_date    500 non-null object
theaters        500 non-null object
tot_gross       500 non-null object
dtypes: datetime64[ns](1), object(6)
memory usage: 27.4+ KB

In [290]:
# Save dataframe as csv
mojo_df.to_csv("mojo_df.csv")
# Save dataframe as pickle
mojo_df.to_pickle("mojo_df.pkl")

### Checkpoint for loading opening box office gross dataframe

In [5]:
# Read dataframe from pickle
mojo_df = pd.read_pickle('mojo_df.pkl')

In [6]:
mojo_df.sample(5)

,movie_name,movie,opening,date_time,release_date,theaters,tot_gross
433,Blade Runner 2049,Blade Runner 2049,"$32,753,122",2017-10-06,10/6/2017,"4,058","$92,054,159"
217,The SpongeBob Movie: Sponge Out of Water,The SpongeBob Movie: Sponge Out of Water,"$55,365,012",2015-02-06,2/6/2015,"3,641","$162,994,032"
285,Sinister 2,Sinister 2,"$10,542,116",2015-08-21,8/21/2015,"2,766","$27,740,955"
116,How to Train Your Dragon 2,How to Train Your Dragon 2,"$49,451,322",2014-06-13,6/13/2014,"4,253","$177,002,924"
0,The Hunger Games: Catching Fire,The Hunger Games: Catching Fire,"$158,074,286",2013-11-22,11/22/2013,"4,163","$424,668,047"

# Scrape Actors & Directors Data From BoxOfficeMojo Using BeautifulSoup

In [7]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import time
import seaborn as sns

### Scraping directors

In [222]:
# define a function that can scrape top 500 directors by total gross in boxofficemojo.com
# scrape director total gross, director average gross, and number of movies
def get_director(soup):
    table = soup.find_all('table')[3]
    director_list = []
    for row in table.find_all('tr')[1:51]:
        cells = row.find_all('td')
        if len(cells) > 0:
            director_name = cells[1].text
            dir_gross = cells[2].text
            num_movies = cells[3].text
            dir_agross = cells[4].text
            cell_dict = {'director': director_name, 'dir_gross': dir_gross, 'dir_nmovies': num_movies, 'dir_agross': dir_agross}
            director_list.append(cell_dict)
    return director_list

In [224]:
# Loop over selected years (2013 - 2017) to scrape movie data
pages = ['1','2','3','4','5','6','7','8','9','10']

def scrape_director(pages):
    director_list = []
    for page in pages:
        url = 'http://www.boxofficemojo.com/people/?view=Director&pagenum=' + page +'&sort=sumgross'
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'lxml')
        if len(director_list) == 0:
            director_list = get_director(soup)
        else:
            director_list = director_list + get_director(soup)
        # pause for 5seconds to limit traffic
        time.sleep(5)
        print("Successfully scraped page" + page + "'s list")
    return director_list
    
director_list = scrape_director(pages)

Successfully scraped page1's list
Successfully scraped page2's list
Successfully scraped page3's list
Successfully scraped page4's list
Successfully scraped page5's list
Successfully scraped page6's list
Successfully scraped page7's list
Successfully scraped page8's list
Successfully scraped page9's list
Successfully scraped page10's list

In [230]:
# #Test case
# page = "2"
# url = 'http://www.boxofficemojo.com/people/?view=Director&pagenum=' + page +'&sort=sumgross'
# response = requests.get(url)
# soup = BeautifulSoup(response.text, 'lxml')
# tb = soup.find_all('table')[3]
# for row in tb.find_all('tr')[1:5]:#.find('table')#[1]#.find('table')
#     print(row.find_all('td')[2].text)

In [233]:
# Convert the list of dictionaries to a pandas dataframe
director_df = pd.DataFrame(director_list)
director_df.sample(5)

    dir_agross dir_gross dir_nmovies             director
236      $40.7    $285.1           7  Catherine Hardwicke
493      $24.2     $72.7           3        Rick Famuyiwa
71      $186.0    $743.8           4            Joe Russo
128      $47.6    $524.1          11         Michael Mann
271      $48.5    $242.5           5           John Moore

In [229]:
# Pickle director dataframe
director_df.to_pickle("director_df.pkl")

### Scraping actor dataset

In [238]:
# define a function that can scrape top 500 actors by total gross in boxofficemojo.com
# scrape director total gross, director average gross, and number of movies
def get_actor(soup):
    table = soup.find_all('table')[3]
    actor_list = []
    for row in table.find_all('tr')[1:51]:
        cells = row.find_all('td')
        if len(cells) > 0:
            actor_name = cells[1].text
            actor_gross = cells[2].text
            actor_nmovies = cells[3].text
            actor_agross = cells[4].text
            cell_dict = {'actor': actor_name, 'act_gross': actor_gross, 'act_nmovies': actor_nmovies,
                         'act_agross': actor_agross}
            actor_list.append(cell_dict)
    return actor_list

In [244]:
# Loop over selected years (2013 - 2017) to scrape movie data
pages = ['1','2','3','4','5','6','7','8','9','10']

def scrape_actor(pages):
    actor_list = []
    for page in pages:
        url = 'http://www.boxofficemojo.com/people/?view=Actor&pagenum=' + page +'&sort=sumgross'
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'lxml')
        if len(actor_list) == 0:
            actor_list = get_actor(soup)
        else:
            actor_list = actor_list + get_actor(soup)
        # pause for 5seconds to limit traffic
        time.sleep(5)
        print("Successfully scraped page" + page + "'s list")
    return actor_list
    
actor_list = scrape_actor(pages)

Successfully scraped page1's list
Successfully scraped page2's list
Successfully scraped page3's list
Successfully scraped page4's list
Successfully scraped page5's list
Successfully scraped page6's list
Successfully scraped page7's list
Successfully scraped page8's list
Successfully scraped page9's list
Successfully scraped page10's list

In [275]:
actor_df = pd.DataFrame(actor_list)
actor_df.sample(5)

    act_agross act_gross act_nmovies           actor
138      $39.8  $1,829.0          46    Danny DeVito
287      $78.1  $1,171.8          15  Mads Mikkelsen
86       $63.6  $2,227.5          35    Mark Ruffalo
154     $443.4  $1,773.6           4    Daisy Ridley
351      $89.4    $983.0          11    Jai Courtney

In [276]:
#remove commas
actor_df.actor = actor_df.actor.replace(",","",regex = True)

In [277]:
#Pickle actor dataframe
actor_df.to_pickle("actor_df.pkl")

### Data cleaning for actors & directors df

In [282]:
# Convert 
omdb_df.imdb = pd.to_numeric(omdb_df.imdb.replace("/10","", regex = True).str.strip())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
act_agross     500 non-null object
act_gross      500 non-null object
act_nmovies    500 non-null object
actor          500 non-null object
dtypes: object(4)
memory usage: 15.7+ KB

# Get Youtube Statistics Using Google API
Reference:
Pulled many bits of code from
https://www.analyticsvidhya.com/blog/2014/09/mining-youtube-python-social-media-analysis/

In [11]:
from apiclient.discovery import build #pip install google-api-python-client
from apiclient.errors import HttpError #pip install google-api-python-client
from oauth2client.tools import argparser #pip install oauth2client
import pandas as pd

In [12]:
DEVELOPER_KEY = "AIzaSyBDbAffV6b-r_fmOFvk6XLE1MoGTwno_bQ" 
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)

In [ ]:
# argparser.add_argument("--q", help="Search term", default="Black Panther trailer")
# #change the default to the search term you want to search
# argparser.add_argument("--max-results", help="Max results", default=5)
# #default number of results which are returned. It can vary from 0 - 100
# args = argparser.parse_args()
# options = args

In [13]:
#Define two functions to be utilized in the next cell:
# 1) get the video id, 2) use the video id to retrieve statistics

# Call the search.list method to retrieve results matching the specified
 # query term.
def get_video_id(movie_name):
    max_results = 1
    trailer = movie_name + "official trailer"
    search_response = youtube.search().list(
     q = trailer,
     type = "video",
     part = "id,snippet",
     maxResults = max_results
    ).execute()
    return search_response

# Get relevant video statistics using video id
def get_statistics(search_response):
    videos = {}
    for search_result in search_response.get("items", []):
        if search_result["id"]["kind"] == "youtube#video":
            videos[search_result["id"]["videoId"]] = search_result["snippet"]["title"]
    # For multiple videos per search, need to merge id's. Not necessary for 1 video
    s = ','.join(videos.keys())
    videos_list_response = youtube.videos().list(
     id = s,
     part='id,statistics'
    ).execute()
    return videos_list_response, videos

In [15]:
# Create a list of dictionaries 
final_list = []
max_results = 1
for movie in mojo_df.movie_name:
    search_response = get_video_id(movie)
    video_response, videos = get_statistics(search_response)
    for i in video_response['items']:
        temp_res = dict(movie_name = movie, v_id = i['id'], v_title = videos[i['id']])
        temp_res.update(i['statistics'])
        final_list.append(temp_res)

In [16]:
# Convert to dataframe
youtube_df = pd.DataFrame(final_list)
youtube_df

,commentCount,dislikeCount,favoriteCount,likeCount,movie_name,v_id,v_title,viewCount
0,9493,1385,0,52030,The Hunger Games: Catching Fire,EAzGXqJSDJ8,The Hunger Games: Catching Fire Official Theat...,12389287
1,1643,259,0,7201,Iron Man 3,oYSD2VQagc4,Iron Man 3 - Official Trailer [HD],1274074
2,7458,8664,0,54157,Frozen,TbQm5doF_Uc,Disney's Frozen Official Trailer,34267342
3,2146,1733,0,17764,Despicable Me 2,koNSa_6Fd1U,Despicable Me 2 Official Trailer #3 (2013) - S...,7725854
4,66568,6511,0,155344,Man of Steel,T6DJcgm3wNY,Man of Steel - Official Trailer 3 [HD],42683390
5,13123,3679,0,32653,Gravity,OiTiKOy59o4,Gravity - Official Main Trailer [2K HD],15729744
6,1290,695,0,8927,Monsters University,QxrQ6BaijAY,Monsters University NEW Trailer (2013) - Pixar...,3375218
7,17057,1629,0,60932,The Hobbit: The Desolation of Smaug,fnaojlfdUbs,The Hobbit: The Desolation of Smaug - Official...,14097771
8,17041,3415,0,78973,Fast & Furious 6,dKi5XoeTN0k,Fast & Furious 6 Official Trailer #1 (2013) - ...,26499303
9,893,179,0,3911,Oz The Great and Powerful,YhLaBpvS7os,Oz the Great and Powerful Official Trailer (20...,1456121
10,5536,741,0,15187,Star Trek Into Darkness,QAEkuVgt6Aw,Star Trek Into Darkness Official Trailer #3 (2...,6688594
11,11763,2486,0,65159,Thor: The Dark World,npvJ9FTgZbM,Thor: The Dark World Official Trailer HD,17863773
12,12925,2206,0,34418,World War Z,Md6Dvxdr0AQ,World War Z Official Trailer #1 (2013) - Brad ...,12098837
13,68,21,0,338,The Croods,3SUkil-muQM,The Croods Official Trailer #1 (2013) - Nicola...,68161
14,323,257,0,3619,The Heat,1O3iRdiplB0,The Heat | Official Trailer [HD] | 20th Centur...,1911975
15,5163,1898,0,35466,We're the Millers,0Vsy5KzsieQ,We're the Millers - Official Trailer [HD],15890698
16,2465,874,0,10132,American Hustle,ST7a1aK_lG0,American Hustle Official TRAILER 1 (2013) - Br...,8459055
17,1140,257,0,4226,The Great Gatsby (2013),OULhlaX6JY4,The Great Gatsby Official Trailer #1 (2012) Le...,1539414
18,3627,1035,0,13586,The Conjuring,ejMMn0t58Lc,The Conjuring Official Trailer #1 (2013) - Ver...,7011251
19,1037,500,0,10200,Identity Thief,uO12W35DpsQ,Identity Thief Official Trailer #2 (2013) - Ja...,4425979
20,2188,908,0,12046,Grown Ups 2,a_c3hW0Uyvc,Grown Ups 2 Official Trailer #1 (2013) - Adam ...,3463529
21,695,164,0,3851,The Wolverine,toLpchTUYk8,The Wolverine Official Trailer #1 (2013) - Hug...,1161650
22,211,118,0,2297,Anchorman 2: The Legend Continues,DwRqg9gZ02M,Anchorman 2: The Legend Continues Official Tra...,533460
23,12529,3108,0,37111,Lone Survivor,yoLFk4JK_RM,Lone Survivor Official Trailer #1 (2013) - Mar...,16448830
24,8743,1551,0,31594,G.I. Joe: Retaliation,V2YMu52MfqA,G.I. Joe 2: Retaliation Trailer Official 2012 ...,21696399
25,152,106,0,1039,Cloudy with a Chance of Meatballs 2,3QCJTbHU60U,Cloudy With a Chance of Meatballs 2 - Official...,836696
26,1403,458,0,14228,Now You See Me,4OtM9j2lcUA,Now You See Me - Official Trailer (HD),5326893
27,11436,2759,0,60801,The Wolf of Wall Street,iszwuX1AK6A,The Wolf of Wall Street Official Trailer,20548674
28,1977,379,0,3537,Lee Daniels' The Butler,FuojHqfe4Vk,The Butler Official Trailer #1 (2013) - Oprah ...,1725274
29,6840,1824,0,36178,The Hangover Part III,KLAkxSjs8ZY,The Hangover Part III Official Trailer #1 (201...,13982084
...,...,...,...,...,...,...,...,...
470,400,245,0,5403,American Assassin,r9rNf-cLWKU,AMERICAN ASSASSIN - Official Trailer - HD (Dyl...,2125097
471,8534,1430,0,78004,The Foreigner,om9YCk7ufHs,The Foreigner Official Trailer #1 (2017) Jacki...,9339280
472,169,26,0,1502,"Everything, Everything",zfKCqYVDNoA,"EVERYTHING, Everything Official Trailer [2017]...",149335
473,898,409,0,5708,Wind River,zN9PDOoLAfg,WIND RIVER - Official US Trailer,3117558
474,5467,5412,0,35397,Geostorm,EuOlYPSEzSc,GEOSTORM - OFFICIAL TRAILER 2 [HD],12582601
475,2884,3046,0,20138,Monster Trucks,wQGawWqJdfs,Monster Trucks Official Trailer #1 (2017) - Lu...,4195580
476,749,677,0,9289,Fist Fight,9aIzXYo6VCE,Fist Fight - Official Trailer [HD],3848102
477,301,202,0,2249,How to be a Latin Lover,--9zIzLfpzo,How To Be A Latin Lover - Official Trailer [US],4238676
478,4033,1356,0,24320,Kidnap (2017),R-Ht8VRPRvU,Kidnap - Official Trailer [HD],7567293
479,1491,632,0,10881,Underworld: Blood Wars,rKHL5PyAPzs,UNDERWORLD: BLOOD WARS - Official Trailer (HD),5333366
480,1404,936,0,12952,The Mountain Between Us,3jyzGKXBOxA,The Mountain Between Us | Official Trailer | 2...,10822199
481,3080,784,0,13882,Life (2017),dgOGqWHtjP0,"Life Official Trailer #1 (2017) Ryan Reynolds,...",4204294
482,24,7,0,347,"I, Tonya",zjDZwOJlxNE,"'I, Tonya' Official Trailer (2017) | Margot Ro...",59106
483,1530,491,0,7325,Hostiles,vJz5l5ru7ws,HOSTILES Official Trailer (2017) Christian Bal...,2316732
484,1354,1342,0,12000,Molly's Game,Vu4UPet8Nyc,Molly's Game | Official Trailer | Own it Now o...,6762396
485,1057,992,0,12394,The Nut Job 2: Nutty by Nature,e5qIZ89hj_A,The Nut Job 2: Nutty by Nature Official Traile...,2975665
486,550,736,0,5839,Rings,K2U-NWDLXM4,Rings Official Trailer #1 (2016) Horror Movie HD,2278242
487,2251,3609,0,26670,Logan Lucky,aPzvKH8AVf0,LOGAN LUCKY | Official HD Trailer,10186232
488,277,294,0,1770,Home Again,y-oFOgFB2uM,Home Again | Official Trailer [HD] | Global R...,4302200
489,4057,3042,0,40004,Resident Evil: The Final Chapter,79Sd4GtOXuI,RESIDENT EVIL: THE FINAL CHAPTER - Official Tr...,10605208
490,959,1308,0,13861,The House,bLwII6-92_Y,"""The House"" Official Trailer",2556207
491,1827,1873,0,14177,All the Money in the World,KXHrCBkIxQQ,ALL THE MONEY IN THE WORLD - Official Trailer ...,4630096
492,4681,1427,0,86404,Gifted,tI01wBXGHUs,Gifted Official Trailer 1 (2017) - Chris Evans...,10490250
493,4506,2126,0,25247,Downsizing,UCrBICYM0yM,Downsizing (2017) - Official Trailer - Paramou...,9556537
494,2861,1419,0,9132,The Bye Bye Man,S2DwrJ9S3f4,The Bye Bye Man | Official Trailer | Own It No...,5889726
495,372,271,0,3276,Victoria and Abdul,SCLcSLxlKkM,Victoria & Abdul - Official Trailer 1 (Univers...,1329162
496,4913,13676,0,21178,Rough Night,oIB4jNYeRY4,ROUGH NIGHT - Official Restricted Trailer (HD),4949341
497,8083,2998,0,34119,My Little Pony: The Movie,aeQe_mZcyf8,My Little Pony: The Movie - Official Trailer D...,4542819
498,1054,530,0,7963,Leap!,GXiDCWxF30U,"Leap! Official Trailer #1 (2017) Elle Fanning,...",1562299
499,4993,1560,0,65876,The Disaster Artist,cMKX2tE5Luk,The Disaster Artist | Official Trailer HD | A24,7279459

In [21]:
# Save dataframe as csv
youtube_df.to_csv("youtube_df_all.csv")
# Save dataframe as pickle
youtube_df.to_pickle("youtube_df_all.pkl")

In [ ]:
# # TEST CODE FOR 1 movie
# movie_name = 'black panther official trailer'

# def get_movie_id(movie_name):
#     movie_name = movie_name
#     max_results = 1
#     search_response = youtube.search().list(
#      q = movie_name + " official trailer",
#      type = "video",
#      part = "id,snippet",
#      maxResults = max_results
#     ).execute()
#     return search_response
# # Add each result to the appropriate list, and then display the lists of
#  # matching videos.
#  # Filter out channels, and playlists.
# def get_statistics(search_response):
#     videos = {}
#     for search_result in search_response.get("items", []):
#         if search_result["id"]["kind"] == "youtube#video":
#             videos[search_result["id"]["videoId"]] = search_result["snippet"]["title"]
#     # For multiple videos per search, need to merge id's. Not necessary for 1 video
#     s = ','.join(videos.keys())
#     videos_list_response = youtube.videos().list(
#      id=s,
#      part='id,statistics'
#     ).execute()
#     return videos_list_response

# res = []
# movie_name = "black panther"
# for i in videos_list_response['items']:
#     temp_res = dict(movie_name = movie_name, v_id = i['id'], v_title = videos[i['id']])
#     temp_res.update(i['statistics'])
#     res.append(temp_res)

### Checkpoint for loading youtube data frame

In [30]:
# Read youtube dataframe from pickle
youtube_df = pd.read_pickle('youtube_df.pkl')

In [33]:
youtube_df.sample(5)

,commentCount,dislikeCount,favoriteCount,likeCount,movie_name,v_id,v_title,viewCount
200,126285,22157,0,710566,Star Wars: The Force Awakens,sGbxmsDFVnE,Star Wars: The Force Awakens Trailer (Official),101357765
243,1140,429,0,10885,The Big Short,LWr8hbUkG9s,The Big Short Official Trailer #1 (2015) - Bra...,4843027
176,3031,986,0,26518,John Wick,C0BMx-qxsP4,John Wick Official Trailer #1 (2014) - Keanu R...,8847713
16,2465,874,0,10132,American Hustle,ST7a1aK_lG0,American Hustle Official TRAILER 1 (2013) - Br...,8459055
92,1110,390,0,21828,One Direction: This is Us,MmqeOZXhycg,One Direction - 1D: This Is Us - Official Movi...,1144445

# Get Google Trends Data Using Selenium

In [49]:
# import selenium and run chromedriver

# !pip install selenium 
# download chromedriver: https://sites.google.com/a/chromium.org/chromedriver/downloads      

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
import time
import os

In [50]:
chromedriver = "/Users/petermin/Downloads/chromedriver" # path to the chromedriver executable
os.environ["webdriver.chrome.driver"] = chromedriver

driver = webdriver.Chrome(chromedriver)
#driver.get("https://trends.google.com/trends/")

In [51]:
# search the movie in google trends
#link with geo set as US and youtube searches
driver.get('https://trends.google.com/trends/explore?geo=US&gprop=youtube')
search_term = driver.find_element_by_css_selector("input")
#time.sleep(1)
search_term.send_keys("Dunkirk")
#time.sleep(2)
search_term.send_keys(Keys.RETURN)

In [36]:
#select_date = Select(driver.find_element_by_css_selector("md-select-value"))
#select_date.click()
#driver.find_element_by_xpath("//md-option[@name='Custom time range...']/option[text()='option_text']").click()

In [35]:
#select_date.select_by_visible_text('select_option_30')

In [34]:
#select_date = Select(driver.find_element_by_css_selector("md-select-value"))
#select_date = Select(driver.find_element_by_id("select_value_label_16"))

#select = driver.find_element_by_xpath("//custom-date-picker/ng-include/md-select")
#driver.find_element_by_xpath("//md-select-value").click()

#driver.find_element_by_id("select_container_18")


# select = driver.find_element_by_xpath("//md-select-menu/md-content")
# for option in select.find_elements_by_tag_name('md-option'):
#     if option.id == "select_option_30":
#         option.click()

In [15]:
from dateutil.relativedelta import relativedelta
import datetime as dt

In [ ]:
# define a function that can scrape top 100 movies of a given year in boxofficemojo.com
# scrape movie name, opening gross, theaters, release date
def get_opening(soup, year):
    table = soup.find_all('table')[4].find_all('tr')[2].find('table')
    movie_list = []
    for row in table.find_all('tr')[2:102]:
        cells = row.find_all('td')
        if len(cells) > 0:
            movie_name = cells[1].text
            tot_gross = cells[3].text
            opening = cells[5].text
            theaters = cells[6].text
            release_date = cells[7].text + "/" + year
            cell_dict = {'movie_name': movie_name, 'tot_gross':tot_gross, 'opening': opening, 'theaters': theaters, 'release_date': release_date}
            movie_list.append(cell_dict)
    return movie_list

In [ ]:
# Scrape google trends data from release
years = ['2013','2014','2015','2016','2017']

def scrape_gtrends(years):
    search_list = []
    for index in range(len(mojo_df)):
        # Scrape google trends starting from 5months prior to movie release date
        url = 'https://trends.google.com/trends/explore?date=' +
        str(mojo_df.datetime[index].date() - relativedelta(months=6)) +
        '%202018-04-18&gprop=youtube&q=' + mojo_df.movie[index]
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'lxml')
        if len(search_list) == 0:
            search_list = get_opening(soup, year)
        else:
            search_list = movie_list + get_gtrends(soup, year)
        # pause for 5seconds to limit traffic
        time.sleep(3)
        if index%10 == 0:
            print("Successfully scraped " + index + "movie searches")
    return search_list
    
movie_list = scrape_gtrends(years)

In [61]:
# Pytrends API
import time
from pytrends.request import TrendReq
pytrends = TrendReq(hl='en-US', tz=360)

In [181]:
# Use pytrends API to collect the youtube search trend(worldwide) for the movie
# starting from 6 months prior to movie release.
# This dataset will be used to normalize the youtube viewcount data
# trend_list is going to be a list of dictionaries to be converted into a dataframe
gtrend_list = []
for i in range(len(mojo_df)):
    kw_list = [mojo_df.movie[i] + " trailer"]
    # start the trend data from 6 months prior to movie release date to Apr 18th
    pytrends.build_payload(kw_list, cat=0, timeframe=
                           str(mojo_df.date_time[i].date() - relativedelta(months=6))
                           + ' 2018-04-18', gprop='youtube')
    raw = pytrends.interest_over_time()
    # if there's not enough searches on google trends and returns empty df, set ratio as 1
    if raw.empty:
        ratio = 1
    # only select search data greater than 3% of highest, in order to not penalize
    # the older videos too much
    else:    
        interest = raw[raw.iloc[:, 0] >= 3].iloc[:,0]
        sum_release = interest[:mojo_df.date_time[i]].sum()
        sum_today = interest.sum()
        ratio = round(sum_release / sum_today, 3)
    trend_dict = {'movie': mojo_df.movie[i], 'gtrend': ratio}
    gtrend_list.append(trend_dict)
    time.sleep(.2)
    if (i + 1) % 50 == 0:
        print("got google trends for", i + 1,"movies")
gtrend_df = pd.DataFrame(gtrend_list)

got google trends for 50 movies
got google trends for 100 movies
got google trends for 150 movies
got google trends for 200 movies
got google trends for 250 movies
got google trends for 300 movies
got google trends for 350 movies
got google trends for 400 movies
got google trends for 450 movies
got google trends for 500 movies

In [193]:
# This code is for setting a cap at 1 year after release date
gtrend2_list = []
for i in range(len(mojo_df)):
    kw_list = [mojo_df.movie[i] + " trailer"]
    # start the trend data from 6 months prior to movie release date to Apr 18th
    if (mojo_df.date_time[i].date() + relativedelta(months=12)) <= mojo_df.date_time[i].date():
        pytrends.build_payload(kw_list, cat=0, timeframe=
                               str(mojo_df.date_time[i].date() - relativedelta(months=6))
                               + " " + str(mojo_df.date_time[i].date() + relativedelta(months=12)),
                               gprop='youtube')
    else:
        pytrends.build_payload(kw_list, cat=0, timeframe=
                               str(mojo_df.date_time[i].date() - relativedelta(months=6))
                               + ' 2018-04-18',
                               gprop='youtube')
    raw = pytrends.interest_over_time()
    # if there's not enough searches on google trends and returns empty df, set ratio as 1
    if raw.empty:
        ratio = 1
    # only select search data greater than 3% of highest, in order to not penalize
    # the older videos too much
    else:    
        interest = raw[raw.iloc[:, 0] >= 3].iloc[:,0]
        sum_release = interest[:mojo_df.date_time[i]].sum()
        sum_today = interest.sum()
        ratio = round(sum_release / sum_today, 3)
    trend_dict = {'movie': mojo_df.movie[i], 'gtrend2': ratio}
    gtrend2_list.append(trend_dict)
    time.sleep(.2)
    if (i + 1) % 50 == 0:
        print("got google trends for", i + 1,"movies")
gtrend2_df = pd.DataFrame(gtrend2_list)

got google trends for 50 movies
got google trends for 100 movies
got google trends for 150 movies
got google trends for 200 movies
got google trends for 250 movies
got google trends for 300 movies
got google trends for 350 movies
got google trends for 400 movies
got google trends for 450 movies
got google trends for 500 movies

In [200]:
#gtrend_df is up to today's date
#gtrend_df is up to 1 year post release date
mergeg_df = pd.merge(gtrend_df,gtrend2_df,on="movie",how="inner")
mojog_df = pd.merge(mojo_df,mergeg_df,on="movie",how="inner")
#Save dataframe
mojog_df.to_pickle("mojog_df.pkl")

In [201]:
mojog_df

,movie_name,movie,opening,date_time,release_date,theaters,tot_gross,gtrend,gtrend2
0,The Hunger Games: Catching Fire,The Hunger Games: Catching Fire,"$158,074,286",2013-11-22,11/22/2013,"4,163","$424,668,047",0.494,0.482
1,Iron Man 3,Iron Man 3,"$174,144,585",2013-05-03,5/3/2013,"4,253","$409,013,994",0.885,0.888
2,Frozen,Frozen,"$243,390",2013-11-22,11/22/2013,1,"$400,738,009",0.124,0.124
3,Despicable Me 2,Despicable Me 2,"$83,517,315",2013-07-03,7/3/2013,"3,997","$368,061,265",0.800,0.810
4,Man of Steel,Man of Steel,"$116,619,362",2013-06-14,6/14/2013,"4,207","$291,045,518",0.812,0.812
5,Gravity,Gravity,"$55,785,112",2013-10-04,10/4/2013,"3,575","$274,092,705",0.272,0.275
6,Monsters University,Monsters University,"$82,429,469",2013-06-21,6/21/2013,"4,004","$268,492,764",0.611,0.611
7,The Hobbit: The Desolation of Smaug,The Hobbit: The Desolation of Smaug,"$73,645,197",2013-12-13,12/13/2013,"3,903","$258,366,855",0.537,0.541
8,Fast & Furious 6,Fast & Furious 6,"$97,375,245",2013-05-24,5/24/2013,"3,658","$238,679,850",0.733,0.747
9,Oz The Great and Powerful,Oz The Great and Powerful,"$79,110,453",2013-03-08,3/8/2013,"3,912","$234,911,825",0.678,0.678
10,Star Trek Into Darkness,Star Trek Into Darkness,"$70,165,559",2013-05-16,5/16/2013,"3,868","$228,778,661",0.816,0.824
11,Thor: The Dark World,Thor: The Dark World,"$85,737,841",2013-11-08,11/8/2013,"3,841","$206,362,140",0.566,0.560
12,World War Z,World War Z,"$66,411,834",2013-06-21,6/21/2013,"3,607","$202,359,711",0.664,0.672
13,The Croods,The Croods,"$43,639,736",2013-03-22,3/22/2013,"4,046","$187,168,425",0.400,0.385
14,The Heat,The Heat,"$39,115,043",2013-06-28,6/28/2013,"3,181","$159,582,188",0.279,0.279
15,We're the Millers,We're the Millers,"$26,419,396",2013-08-07,8/7/2013,"3,260","$150,394,119",0.463,0.457
16,American Hustle,American Hustle,"$740,455",2013-12-13,12/13/2013,6,"$150,117,807",0.169,0.169
17,The Great Gatsby (2013),The Great Gatsby,"$50,085,185",2013-05-10,5/10/2013,"3,535","$144,840,419",0.649,0.651
18,The Conjuring,The Conjuring,"$41,855,326",2013-07-19,7/19/2013,"2,903","$137,400,141",0.258,0.252
19,Identity Thief,Identity Thief,"$34,551,025",2013-02-08,2/8/2013,"3,141","$134,506,920",0.267,0.270
20,Grown Ups 2,Grown Ups 2,"$41,508,572",2013-07-12,7/12/2013,"3,491","$133,668,525",0.669,0.669
21,The Wolverine,The Wolverine,"$53,113,752",2013-07-26,7/26/2013,"3,924","$132,556,852",0.546,0.551
22,Anchorman 2: The Legend Continues,Anchorman 2: The Legend Continues,"$26,232,425",2013-12-18,12/18/2013,"3,507","$125,168,368",0.209,0.209
23,Lone Survivor,Lone Survivor,"$90,872",2013-12-25,12/25/2013,2,"$125,095,601",0.213,0.213
24,G.I. Joe: Retaliation,G.I. Joe: Retaliation,"$40,501,814",2013-03-28,3/28/2013,"3,719","$122,523,060",0.523,0.523
25,Cloudy with a Chance of Meatballs 2,Cloudy with a Chance of Meatballs 2,"$34,017,930",2013-09-27,9/27/2013,"4,001","$119,793,567",0.388,0.388
26,Now You See Me,Now You See Me,"$29,350,389",2013-05-31,5/31/2013,"2,925","$117,723,989",0.101,0.101
27,The Wolf of Wall Street,The Wolf of Wall Street,"$18,361,578",2013-12-25,12/25/2013,"2,537","$116,900,694",0.258,0.249
28,Lee Daniels' The Butler,Lee Daniels' The Butler,"$24,637,312",2013-08-16,8/16/2013,"2,933","$116,632,095",0.207,0.218
29,The Hangover Part III,The Hangover Part III,"$41,671,198",2013-05-23,5/23/2013,"3,555","$112,200,072",0.657,0.559
...,...,...,...,...,...,...,...,...,...
470,American Assassin,American Assassin,"$14,846,778",2017-09-15,9/15/2017,"3,154","$36,249,674",0.293,0.293
471,The Foreigner,The Foreigner,"$13,113,024",2017-10-13,10/13/2017,"2,515","$34,393,507",0.354,0.354
472,"Everything, Everything","Everything, Everything","$11,727,390",2017-05-19,5/19/2017,"2,801","$34,121,140",0.338,0.281
473,Wind River,Wind River,"$161,558",2017-08-04,8/4/2017,4,"$33,800,859",0.050,0.064
474,Geostorm,Geostorm,"$13,707,376",2017-10-20,10/20/2017,"3,246","$33,700,160",0.318,0.321
475,Monster Trucks,Monster Trucks,"$10,950,705",2017-01-13,1/13/2017,"3,119","$33,370,166",0.356,0.356
476,Fist Fight,Fist Fight,"$12,201,873",2017-02-17,2/17/2017,"3,185","$32,187,017",0.243,0.248
477,How to be a Latin Lover,How to be a Latin Lover,"$12,252,439",2017-04-28,4/28/2017,"1,118","$32,149,404",0.232,0.230
478,Kidnap (2017),Kidnap,"$10,016,323",2017-08-04,8/4/2017,"2,378","$30,718,107",0.458,0.457
479,Underworld: Blood Wars,Underworld: Blood Wars,"$13,688,751",2017-01-06,1/6/2017,"3,070","$30,353,973",0.613,0.617
480,The Mountain Between Us,The Mountain Between Us,"$10,551,336",2017-10-06,10/6/2017,"3,088","$30,348,555",0.194,0.203
481,Life (2017),Life,"$12,501,936",2017-03-24,3/24/2017,"3,146","$30,234,022",0.358,0.358
482,"I, Tonya","I, Tonya","$264,155",2017-12-08,12/8/2017,4,"$30,006,215",0.205,0.216
483,Hostiles,Hostiles,"$22,849",2017-12-22,12/22/2017,3,"$29,812,876",0.151,0.156
484,Molly's Game,Molly's Game,"$2,349,967",2017-12-25,12/25/2017,271,"$28,780,744",0.236,0.188
485,The Nut Job 2: Nutty by Nature,The Nut Job 2: Nutty by Nature,"$8,342,311",2017-08-11,8/11/2017,"4,003","$28,370,522",0.218,0.170
486,Rings,Rings,"$13,002,632",2017-02-03,2/3/2017,"2,931","$27,793,018",0.386,0.375
487,Logan Lucky,Logan Lucky,"$7,600,036",2017-08-18,8/18/2017,"3,031","$27,780,977",0.225,0.229
488,Home Again,Home Again,"$8,567,881",2017-09-08,9/8/2017,"2,940","$27,020,284",0.224,0.225
489,Resident Evil: The Final Chapter,Resident Evil: The Final Chapter,"$13,601,682",2017-01-27,1/27/2017,"3,104","$26,830,068",0.583,0.536
490,The House,The House,"$8,724,795",2017-06-30,6/30/2017,"3,134","$25,584,504",0.358,0.352
491,All the Money in the World,All the Money in the World,"$5,584,684",2017-12-25,12/25/2017,"2,074","$25,113,707",0.382,0.379
492,Gifted,Gifted,"$446,380",2017-04-07,4/7/2017,56,"$24,801,212",0.104,0.109
493,Downsizing,Downsizing,"$4,954,287",2017-12-22,12/22/2017,"2,668","$24,449,754",0.438,0.438
494,The Bye Bye Man,The Bye Bye Man,"$13,501,349",2017-01-13,1/13/2017,"2,220","$22,395,806",0.288,0.277
495,Victoria and Abdul,Victoria and Abdul,"$158,845",2017-09-22,9/22/2017,4,"$22,245,070",0.343,0.311
496,Rough Night,Rough Night,"$8,004,283",2017-06-16,6/16/2017,"3,162","$22,105,643",0.454,0.454
497,My Little Pony: The Movie,My Little Pony: The Movie,"$8,885,899",2017-10-06,10/6/2017,"2,528","$21,885,107",0.632,0.632
498,Leap!,Leap!,"$4,730,038",2017-08-25,8/25/2017,"2,575","$21,858,070",1.000,1.000
499,The Disaster Artist,The Disaster Artist,"$1,211,345",2017-12-01,12/1/2017,19,"$21,120,616",0.383,0.401

In [142]:
#Test code
# #str(mojo_df.date_time[i].date() - relativedelta(months=6)) + ' 2018-04-18'
# #kw_list = [mojo_df.movie[i] + " trailer"]
# kw_list = ["Tyler Perry's A Madea Christmas" + " trailer"]

# pytrends.build_payload(kw_list, cat=0, timeframe=
#                            str(mojo_df.date_time[66].date() - relativedelta(months=6))
#                            + ' 2018-04-18', gprop='youtube')
#     #artificially subtract 1 from interest data to reduce penalty on older videos
# raw = pytrends.interest_over_time()

# raw.empty

True

# Get OMDB data through Google API

In [80]:
#pip install omdb
import omdb
import json
import time

In [129]:
# Set API activation key
omdb.set_default('apikey', 74553915)

In [95]:
unfetched = ["Jackass Presents: Bad Grandpa","Hansel and Gretel: Witch Hunters","Tyler Perry's A Madea Christmas",
            "Tyler Perry's Temptation: Confessions of a Marriage Counselor",
            "Pain and Gain", "Jurassic Park 3D", "Walking with Dinosaurs", "Texas Chainsaw 3D", "21 and Over"
            ]

In [130]:
# Create a list of dictionaries 
#initialize
omdb_list = []
counter = 1

for movie_name in mojo_df.movie:
    res = omdb.request(t=movie_name)
    time.sleep(3)
    res_str = res.content.decode('utf-8')
    res_obj = json.loads(res_str)
    try:
        res_dict = dict(movie = movie_name, 
                        imdb = res_obj["Ratings"][0]["Value"],  
                        rotten_tomatoes = res_obj["Ratings"][1]["Value"],
                        metacritic = res_obj["Ratings"][2]["Value"], 
                        runtime = res_obj["Runtime"],
                        year = res_obj["Year"],
                        rated = res_obj["Rated"],
                        actors = res_obj["Actors"],
                        director = res_obj["Director"]
                       )
        omdb_list.append(res_dict)
    except:
        print("unable to fetch data for", movie_name)
        unfetched.append(movie_name)
        pass
    counter += 1
    if counter % 10 == 0:
        print("fetched", counter, "movie data")

unable to fetch data for Entourage
unable to fetch data for The Lazarus Effect
fetched 300 movie data
unable to fetch data for The Divergent Series: Allegiant
unable to fetch data for 13 Hours: The Secret Soldiers of Benghazi
fetched 400 movie data
unable to fetch data for John Wick: Chapter Two
unable to fetch data for Tyler Perry's Boo 2! A Madea Halloween
unable to fetch data for xXx: The Return of Xander Cage
unable to fetch data for 47 Meters Down
unable to fetch data for Victoria and Abdul

In [133]:
# Save omdb dataframe
omdb_df = pd.DataFrame(omdb_list)

In [141]:
# This should add up to 500
#len(unfetched)
len(omdb_list)+len(unfetched)

500

In [138]:
# Save dataframe as csv
omdb_df.to_csv("omdb_df.csv")
# Save dataframe as pickle
omdb_df.to_pickle("omdb_df.pkl")

In [42]:
# #Sample code for 1 request
# a='Entourage'
# res = omdb.request(t=a)
# res_str = res.content.decode('utf-8')
# res_obj = json.loads(res_str)
# res_obj

### Checkpoint for loading omdb dataframe

In [144]:
# Read youtube dataframe from pickle
omdb_df = pd.read_pickle('omdb_df.pkl')
len(omdb_df)

480

In [110]:
omdb_df

,actors,director,imdb,metacritic,movie,rated,rotten_tomatoes,runtime,year
0,"Jennifer Lawrence, Liam Hemsworth, Jack Quaid,...",Francis Lawrence,7.5,76,The Hunger Games: Catching Fire,PG-13,89,146,2013
1,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...",Shane Black,7.2,62,Iron Man 3,PG-13,80,130,2013
2,"Kristen Bell, Idina Menzel, Jonathan Groff, Jo...","Chris Buck, Jennifer Lee",7.5,74,Frozen,PG,90,102,2013
3,"Steve Carell, Kristen Wiig, Benjamin Bratt, Mi...","Pierre Coffin, Chris Renaud",7.4,62,Despicable Me 2,PG,74,98,2013
4,"Henry Cavill, Amy Adams, Michael Shannon, Dian...",Zack Snyder,7.1,55,Man of Steel,PG-13,55,143,2013
5,"Sandra Bullock, George Clooney, Ed Harris, Ort...",Alfonso Cuarón,7.8,96,Gravity,PG-13,96,91,2013
6,"Billy Crystal, John Goodman, Steve Buscemi, He...",Dan Scanlon,7.3,65,Monsters University,G,79,104,2013
7,"Ian McKellen, Martin Freeman, Richard Armitage...",Peter Jackson,7.9,66,The Hobbit: The Desolation of Smaug,PG-13,74,161,2013
8,"Vin Diesel, Paul Walker, Dwayne Johnson, Jorda...",Justin Lin,7.1,61,Fast & Furious 6,PG-13,69,130,2013
9,"James Franco, Mila Kunis, Rachel Weisz, Michel...",Sam Raimi,6.3,44,Oz The Great and Powerful,PG,59,130,2013
10,"Chris Pine, Zachary Quinto, Zoe Saldana, Karl ...",J.J. Abrams,7.8,72,Star Trek Into Darkness,PG-13,86,132,2013
11,"Chris Hemsworth, Natalie Portman, Tom Hiddlest...",Alan Taylor,7.0,54,Thor: The Dark World,PG-13,66,112,2013
12,"Brad Pitt, Mireille Enos, Daniella Kertesz, Ja...",Marc Forster,7.0,63,World War Z,PG-13,66,116,2013
13,"Nicolas Cage, Emma Stone, Ryan Reynolds, Cathe...","Kirk De Micco, Chris Sanders",7.2,55,The Croods,PG,72,98,2013
14,"Sandra Bullock, Melissa McCarthy, Demián Bichi...",Paul Feig,6.6,60,The Heat,R,65,117,2013
15,"Jennifer Aniston, Jason Sudeikis, Emma Roberts...",Rawson Marshall Thurber,7.0,44,We're the Millers,R,47,110,2013
16,"Christian Bale, Bradley Cooper, Amy Adams, Jer...",David O. Russell,7.3,90,American Hustle,R,93,138,2013
17,"Lisa Adam, Frank Aldridge, Amitabh Bachchan, S...",Baz Luhrmann,7.3,55,The Great Gatsby,PG-13,49,143,2013
18,"Vera Farmiga, Patrick Wilson, Lili Taylor, Ron...",James Wan,7.5,68,The Conjuring,R,86,112,2013
19,"Jason Bateman, Melissa McCarthy, Jon Favreau, ...",Seth Gordon,5.7,35,Identity Thief,R,19,111,2013
20,"Adam Sandler, Kevin James, Chris Rock, David S...",Dennis Dugan,5.4,19,Grown Ups 2,PG-13,7,101,2013
21,"Hugh Jackman, Tao Okamoto, Rila Fukushima, Hir...",James Mangold,6.7,60,The Wolverine,PG-13,69,126,2013
22,"Will Ferrell, Steve Carell, Paul Rudd, David K...",Adam McKay,6.3,61,Anchorman 2: The Legend Continues,PG-13,75,119,2013
23,"Mark Wahlberg, Taylor Kitsch, Emile Hirsch, Be...",Peter Berg,7.5,60,Lone Survivor,R,76,121,2013
24,"Dwayne Johnson, Jonathan Pryce, Byung-hun Lee,...",Jon M. Chu,5.8,41,G.I. Joe: Retaliation,PG-13,28,110,2013
25,"Bill Hader, Anna Faris, James Caan, Will Forte","Cody Cameron, Kris Pearn",6.4,59,Cloudy with a Chance of Meatballs 2,PG,71,95,2013
26,"Jesse Eisenberg, Mark Ruffalo, Woody Harrelson...",Louis Leterrier,7.3,50,Now You See Me,PG-13,50,115,2013
27,"Leonardo DiCaprio, Jonah Hill, Margot Robbie, ...",Martin Scorsese,8.2,75,The Wolf of Wall Street,R,78,180,2013
28,"Forest Whitaker, David Banner, Michael Rainey ...",Lee Daniels,7.2,66,Lee Daniels' The Butler,PG-13,72,132,2013
29,"Bradley Cooper, Ed Helms, Zach Galifianakis, J...",Todd Phillips,5.9,30,The Hangover Part III,R,21,100,2013
...,...,...,...,...,...,...,...,...,...
450,"Matt Passmore, Tobin Bell, Callum Keith Rennie...","Michael Spierig, Peter Spierig",5.8,39,Jigsaw,R,34,92,2017
451,"Dylan O'Brien, Charlotte Vega, Christopher Bom...",Michael Cuesta,6.2,45,American Assassin,R,34,112,2017
452,"Katie Leung, Jackie Chan, Rufus Jones, Mark Tandy",Martin Campbell,7.0,55,The Foreigner,R,62,113,2017
453,"Amandla Stenberg, Nick Robinson, Anika Noni Ro...",Stella Meghie,6.4,52,"Everything, Everything",PG-13,46,96,2017
454,"Kelsey Asbille, Jeremy Renner, Julia Jones, Te...",Taylor Sheridan,7.8,73,Wind River,R,87,107,2017
455,"Gerard Butler, Jim Sturgess, Abbie Cornish, Al...",Dean Devlin,5.4,21,Geostorm,PG-13,13,109,2017
456,"Lucas Till, Jane Levy, Thomas Lennon, Barry Pe...",Chris Wedge,5.7,41,Monster Trucks,PG,30,104,2016
457,"Charlie Day, Ice Cube, Tracy Morgan, Jillian Bell",Richie Keen,5.6,37,Fist Fight,R,26,91,2017
458,"Eugenio Derbez, Salma Hayek, Raphael Alejandro...",Ken Marino,5.9,54,How to be a Latin Lover,PG-13,38,115,2017
459,"Halle Berry, Sage Correa, Chris McGinn, Lew Te...",Luis Prieto,5.9,44,Kidnap,R,37,95,2017
460,"Kate Beckinsale, Theo James, Tobias Menzies, L...",Anna Foerster,5.8,23,Underworld: Blood Wars,R,20,91,2016
461,"Idris Elba, Kate Winslet, Beau Bridges, Dermot...",Hany Abu-Assad,6.4,48,The Mountain Between Us,PG-13,40,112,2017
462,"Hiroyuki Sanada, Ryan Reynolds, Rebecca Fergus...",Daniel Espinosa,6.6,54,Life,R,67,104,2017
463,"Margot Robbie, Sebastian Stan, Allison Janney,...",Craig Gillespie,7.6,77,"I, Tonya",R,90,120,2017
464,"Scott Shepherd, Rosamund Pike, Ava Cooper, Ste...",Scott Cooper,7.3,65,Hostiles,R,73,134,2017
465,"Jessica Chastain, Idris Elba, Kevin Costner, M...",Aaron Sorkin,7.5,71,Molly's Game,R,82,140,2017
466,"Will Arnett, Maya Rudolph, Bobby Cannavale, Bo...",Cal Brunker,5.3,36,The Nut Job 2: Nutty by Nature,PG,13,91,2017
467,"Matilda Anna Ingrid Lutz, Alex Roe, Johnny Gal...",F. Javier Gutiérrez,4.5,25,Rings,PG-13,7,102,2017
468,"Farrah Mackenzie, Channing Tatum, Jim O'Heir, ...",Steven Soderbergh,7.1,78,Logan Lucky,PG-13,93,118,2017
469,"Reese Witherspoon, Michael Sheen, Candice Berg...",Hallie Meyers-Shyer,5.7,41,Home Again,PG-13,32,97,2017
470,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",Paul W.S. Anderson,5.6,49,Resident Evil: The Final Chapter,R,36,107,2016
471,"Will Ferrell, Amy Poehler, Jason Mantzoukas, R...",Andrew Jay Cohen,5.6,30,The House,R,18,88,2017
472,"Michelle Williams, Christopher Plummer, Mark W...",Ridley Scott,7.0,72,All the Money in the World,R,78,132,2017
473,"Chris Evans, Mckenna Grace, Lindsay Duncan, Oc...",Marc Webb,7.6,60,Gifted,PG-13,73,101,2017
474,"Matt Damon, Christoph Waltz, Hong Chau, Kriste...",Alexander Payne,5.7,63,Downsizing,R,51,135,2017
475,"Douglas Smith, Lucien Laviscount, Cressida Bon...",Stacy Title,4.3,37,The Bye Bye Man,PG-13,23,97,2017
476,"Scarlett Johansson, Jillian Bell, Zoë Kravitz,...",Lucia Aniello,5.2,51,Rough Night,R,45,101,2017
477,"Uzo Aduba, Ashleigh Ball, Adam Bengis, Emily B...",Jayson Thiessen,6.2,39,My Little Pony: The Movie,PG,47,99,2017
478,"Elle Fanning, Dane DeHaan, Carly Rae Jepsen, M...","Eric Summer, Éric Warin, Mimi Maynard, Paulett...",6.8,48,Leap!,PG,37,89,2016
479,"Dave Franco, James Franco, Seth Rogen, Ari Gra...",James Franco,7.6,76,The Disaster Artist,R,91,104,2017

# Some data cleaning prior to merge

In [95]:
# Import all the dataframes
mojo_df = pd.read_pickle('mojo_df.pkl')
youtube_df = pd.read_pickle('youtube_df.pkl')
omdb_df = pd.read_pickle('omdb_df.pkl')

In [96]:
#clean mojo df data
mojo_df.opening = mojo_df.opening.replace("\$","", regex = True).replace(",","", regex = True).str.strip()
mojo_df.opening = pd.to_numeric(mojo_df.opening)
mojo_df.theaters = mojo_df.theaters.replace(",","", regex = True).str.strip()
mojo_df.theaters = pd.to_numeric(mojo_df.theaters)
mojo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
movie_name      500 non-null object
movie           500 non-null object
opening         500 non-null int64
date_time       500 non-null datetime64[ns]
release_date    500 non-null object
theaters        500 non-null int64
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 23.5+ KB

In [97]:
# select youtube df relevant data
youtube_df = youtube_df[["movie_name", "viewCount", "commentCount", "dislikeCount", "likeCount"]]

#replace nulls with 0
youtube_df = youtube_df.fillna(0)
# convert numeric str values to int
youtube_df.viewCount = pd.to_numeric(youtube_df.viewCount)
youtube_df.dislikeCount = pd.to_numeric(youtube_df.dislikeCount)
youtube_df.commentCount = pd.to_numeric(youtube_df.commentCount)
youtube_df.likeCount = pd.to_numeric(youtube_df.likeCount)
youtube_df = youtube_df.rename(columns ={"viewCount":"Yviews", "commentCount": "Ycomments", 
                                         "dislikeCount": "Ydislikes", "likeCount":"Ylikes"})
youtube_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
movie_name    500 non-null object
Yviews        500 non-null int64
Ycomments     500 non-null int64
Ydislikes     500 non-null int64
Ylikes        500 non-null int64
dtypes: int64(4), object(1)
memory usage: 19.6+ KB

In [98]:
# Clean omdb data
omdb_df.imdb = pd.to_numeric(omdb_df.imdb.replace("/10","", regex = True).str.strip())
omdb_df.metacritic = pd.to_numeric(omdb_df.metacritic.replace("/100","", regex = True).str.strip())
omdb_df.rotten_tomatoes = pd.to_numeric(omdb_df.rotten_tomatoes.replace("%","", regex = True).str.strip())
omdb_df.runtime = pd.to_numeric(omdb_df.runtime.replace("min","", regex = True).str.strip())
omdb_df.year = pd.to_numeric(omdb_df.year)
omdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 9 columns):
actors             480 non-null object
director           480 non-null object
imdb               480 non-null float64
metacritic         480 non-null int64
movie              480 non-null object
rated              480 non-null object
rotten_tomatoes    480 non-null int64
runtime            480 non-null int64
year               480 non-null int64
dtypes: float64(1), int64(4), object(4)
memory usage: 33.8+ KB

In [99]:
# print length of each dataset
print(len(mojo_df), len(youtube_df), len(omdb_df))

500 500 480

## Merge the dataframes

In [106]:
merged = pd.DataFrame.merge(mojo_df,youtube_df,on='movie_name', how = 'inner')
merged = merged.drop(["release_date"],1)
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 9 columns):
movie_name    500 non-null object
movie         500 non-null object
opening       500 non-null int64
date_time     500 non-null datetime64[ns]
theaters      500 non-null int64
Yviews        500 non-null int64
Ycomments     500 non-null int64
Ydislikes     500 non-null int64
Ylikes        500 non-null int64
dtypes: datetime64[ns](1), int64(6), object(2)
memory usage: 39.1+ KB

In [155]:
merged2 = pd.DataFrame.merge(merged,omdb_df,on="movie",how="inner")
year = [2013,2014,2015,2016,2017]
# Remove 11 movies that have been wrongly identified on omdb (wrong year)
merged2 = merged2[merged2.year.isin(year)]
merged2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 479
Data columns (total 17 columns):
movie_name         469 non-null object
movie              469 non-null object
opening            469 non-null int64
date_time          469 non-null datetime64[ns]
theaters           469 non-null int64
Yviews             469 non-null int64
Ycomments          469 non-null int64
Ydislikes          469 non-null int64
Ylikes             469 non-null int64
actors             469 non-null object
director           469 non-null object
imdb               469 non-null float64
metacritic         469 non-null int64
rated              469 non-null object
rotten_tomatoes    469 non-null int64
runtime            469 non-null int64
year               469 non-null int64
dtypes: datetime64[ns](1), float64(1), int64(10), object(5)
memory usage: 66.0+ KB

## Scale opening gross to year

In [156]:
# First create a dataframe for year and corresponding movie ticket
year = [2013,2014,2015,2016,2017]
tick = [8.13,8.17,8.43,8.65,8.97]
adjuster = pd.DataFrame({"year":year,"tick":tick})
adjuster.head()

   tick  year
0  8.13  2013
1  8.17  2014
2  8.43  2015
3  8.65  2016
4  8.97  2017

In [157]:
# Merge adjuster with merged2
merged2 = pd.merge(merged2,adjuster,on="year",how="inner")
merged2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 469 entries, 0 to 468
Data columns (total 18 columns):
movie_name         469 non-null object
movie              469 non-null object
opening            469 non-null int64
date_time          469 non-null datetime64[ns]
theaters           469 non-null int64
Yviews             469 non-null int64
Ycomments          469 non-null int64
Ydislikes          469 non-null int64
Ylikes             469 non-null int64
actors             469 non-null object
director           469 non-null object
imdb               469 non-null float64
metacritic         469 non-null int64
rated              469 non-null object
rotten_tomatoes    469 non-null int64
runtime            469 non-null int64
year               469 non-null int64
tick               469 non-null float64
dtypes: datetime64[ns](1), float64(2), int64(10), object(5)
memory usage: 69.6+ KB

In [158]:
# Create new column
est_tick = (merged2.opening // merged2.tick).astype("int64")
merged2.insert(loc=3, column='est_tick', value=est_tick)
merged2 = merged2.rename(columns={"opening":"op_gross"})

In [283]:
merged2

,movie_name,movie,op_gross,est_tick,date_time,theaters,Yviews,Ycomments,Ydislikes,Ylikes,actors,director,imdb,metacritic,rated,rotten_tomatoes,runtime,year,tick
0,The Hunger Games: Catching Fire,The Hunger Games: Catching Fire,158074286,19443331,2013-11-22,4163,12389287,9493,1385,52030,"Jennifer Lawrence, Liam Hemsworth, Jack Quaid,...",Francis Lawrence,7.5,76,PG-13,89,146,2013,8.13
1,Iron Man 3,Iron Man 3,174144585,21419998,2013-05-03,4253,1274074,1643,259,7201,"Robert Downey Jr., Gwyneth Paltrow, Don Cheadl...",Shane Black,7.2,62,PG-13,80,130,2013,8.13
2,Frozen,Frozen,243390,29937,2013-11-22,1,34267342,7458,8664,54157,"Kristen Bell, Idina Menzel, Jonathan Groff, Jo...","Chris Buck, Jennifer Lee",7.5,74,PG,90,102,2013,8.13
3,Despicable Me 2,Despicable Me 2,83517315,10272732,2013-07-03,3997,7725854,2146,1733,17764,"Steve Carell, Kristen Wiig, Benjamin Bratt, Mi...","Pierre Coffin, Chris Renaud",7.4,62,PG,74,98,2013,8.13
4,Man of Steel,Man of Steel,116619362,14344324,2013-06-14,4207,42683390,66568,6511,155344,"Henry Cavill, Amy Adams, Michael Shannon, Dian...",Zack Snyder,7.1,55,PG-13,55,143,2013,8.13
5,Gravity,Gravity,55785112,6861637,2013-10-04,3575,15729744,13123,3679,32653,"Sandra Bullock, George Clooney, Ed Harris, Ort...",Alfonso Cuarón,7.8,96,PG-13,96,91,2013,8.13
6,Monsters University,Monsters University,82429469,10138926,2013-06-21,4004,3375218,1290,695,8927,"Billy Crystal, John Goodman, Steve Buscemi, He...",Dan Scanlon,7.3,65,G,79,104,2013,8.13
7,The Hobbit: The Desolation of Smaug,The Hobbit: The Desolation of Smaug,73645197,9058449,2013-12-13,3903,14097771,17057,1629,60932,"Ian McKellen, Martin Freeman, Richard Armitage...",Peter Jackson,7.9,66,PG-13,74,161,2013,8.13
8,Fast & Furious 6,Fast & Furious 6,97375245,11977274,2013-05-24,3658,26499303,17041,3415,78973,"Vin Diesel, Paul Walker, Dwayne Johnson, Jorda...",Justin Lin,7.1,61,PG-13,69,130,2013,8.13
9,Oz The Great and Powerful,Oz The Great and Powerful,79110453,9730683,2013-03-08,3912,1456121,893,179,3911,"James Franco, Mila Kunis, Rachel Weisz, Michel...",Sam Raimi,6.3,44,PG,59,130,2013,8.13
10,Star Trek Into Darkness,Star Trek Into Darkness,70165559,8630450,2013-05-16,3868,6688594,5536,741,15187,"Chris Pine, Zachary Quinto, Zoe Saldana, Karl ...",J.J. Abrams,7.8,72,PG-13,86,132,2013,8.13
11,Thor: The Dark World,Thor: The Dark World,85737841,10545859,2013-11-08,3841,17863773,11763,2486,65159,"Chris Hemsworth, Natalie Portman, Tom Hiddlest...",Alan Taylor,7.0,54,PG-13,66,112,2013,8.13
12,World War Z,World War Z,66411834,8168737,2013-06-21,3607,12098837,12925,2206,34418,"Brad Pitt, Mireille Enos, Daniella Kertesz, Ja...",Marc Forster,7.0,63,PG-13,66,116,2013,8.13
13,The Croods,The Croods,43639736,5367741,2013-03-22,4046,68161,68,21,338,"Nicolas Cage, Emma Stone, Ryan Reynolds, Cathe...","Kirk De Micco, Chris Sanders",7.2,55,PG,72,98,2013,8.13
14,The Heat,The Heat,39115043,4811198,2013-06-28,3181,1911975,323,257,3619,"Sandra Bullock, Melissa McCarthy, Demián Bichi...",Paul Feig,6.6,60,R,65,117,2013,8.13
15,We're the Millers,We're the Millers,26419396,3249618,2013-08-07,3260,15890698,5163,1898,35466,"Jennifer Aniston, Jason Sudeikis, Emma Roberts...",Rawson Marshall Thurber,7.0,44,R,47,110,2013,8.13
16,American Hustle,American Hustle,740455,91076,2013-12-13,6,8459055,2465,874,10132,"Christian Bale, Bradley Cooper, Amy Adams, Jer...",David O. Russell,7.3,90,R,93,138,2013,8.13
17,The Great Gatsby (2013),The Great Gatsby,50085185,6160539,2013-05-10,3535,1539414,1140,257,4226,"Lisa Adam, Frank Aldridge, Amitabh Bachchan, S...",Baz Luhrmann,7.3,55,PG-13,49,143,2013,8.13
18,The Conjuring,The Conjuring,41855326,5148256,2013-07-19,2903,7011251,3627,1035,13586,"Vera Farmiga, Patrick Wilson, Lili Taylor, Ron...",James Wan,7.5,68,R,86,112,2013,8.13
19,Identity Thief,Identity Thief,34551025,4249818,2013-02-08,3141,4425979,1037,500,10200,"Jason Bateman, Melissa McCarthy, Jon Favreau, ...",Seth Gordon,5.7,35,R,19,111,2013,8.13
20,Grown Ups 2,Grown Ups 2,41508572,5105605,2013-07-12,3491,3463529,2188,908,12046,"Adam Sandler, Kevin James, Chris Rock, David S...",Dennis Dugan,5.4,19,PG-13,7,101,2013,8.13
21,The Wolverine,The Wolverine,53113752,6533056,2013-07-26,3924,1161650,695,164,3851,"Hugh Jackman, Tao Okamoto, Rila Fukushima, Hir...",James Mangold,6.7,60,PG-13,69,126,2013,8.13
22,Anchorman 2: The Legend Continues,Anchorman 2: The Legend Continues,26232425,3226620,2013-12-18,3507,533460,211,118,2297,"Will Ferrell, Steve Carell, Paul Rudd, David K...",Adam McKay,6.3,61,PG-13,75,119,2013,8.13
23,Lone Survivor,Lone Survivor,90872,11177,2013-12-25,2,16448830,12529,3108,37111,"Mark Wahlberg, Taylor Kitsch, Emile Hirsch, Be...",Peter Berg,7.5,60,R,76,121,2013,8.13
24,G.I. Joe: Retaliation,G.I. Joe: Retaliation,40501814,4981772,2013-03-28,3719,21696399,8743,1551,31594,"Dwayne Johnson, Jonathan Pryce, Byung-hun Lee,...",Jon M. Chu,5.8,41,PG-13,28,110,2013,8.13
25,Cloudy with a Chance of Meatballs 2,Cloudy with a Chance of Meatballs 2,34017930,4184247,2013-09-27,4001,836696,152,106,1039,"Bill Hader, Anna Faris, James Caan, Will Forte","Cody Cameron, Kris Pearn",6.4,59,PG,71,95,2013,8.13
26,Now You See Me,Now You See Me,29350389,3610133,2013-05-31,2925,5326893,1403,458,14228,"Jesse Eisenberg, Mark Ruffalo, Woody Harrelson...",Louis Leterrier,7.3,50,PG-13,50,115,2013,8.13
27,The Wolf of Wall Street,The Wolf of Wall Street,18361578,2258496,2013-12-25,2537,20548674,11436,2759,60801,"Leonardo DiCaprio, Jonah Hill, Margot Robbie, ...",Martin Scorsese,8.2,75,R,78,180,2013,8.13
28,Lee Daniels' The Butler,Lee Daniels' The Butler,24637312,3030419,2013-08-16,2933,1725274,1977,379,3537,"Forest Whitaker, David Banner, Michael Rainey ...",Lee Daniels,7.2,66,PG-13,72,132,2013,8.13
29,The Hangover Part III,The Hangover Part III,41671198,5125608,2013-05-23,3555,13982084,6840,1824,36178,"Bradley Cooper, Ed Helms, Zach Galifianakis, J...",Todd Phillips,5.9,30,R,21,100,2013,8.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,Valerian and the City of a Thousand Planets,Valerian and the City of a Thousand Planets,17007624,1896056,2017-07-21,3553,2329843,2241,1102,17965,"Dane DeHaan, Cara Delevingne, Clive Owen, Rihanna",Luc Besson,6.5,51,PG-13,49,137,2017,8.97
440,The Star,The Star,9812674,1093943,2017-11-17,2837,2508999,1,989,2972,"Steven Yeun, Keegan-Michael Key, Aidy Bryant, ...",Timothy Reckart,5.8,42,PG,45,86,2017,8.97
441,Ghost in the Shell (2017),Ghost in the Shell,18676033,2082054,2017-03-31,3440,30351184,28934,21188,165544,"Scarlett Johansson, Pilou Asbæk, Takeshi Kitan...",Rupert Sanders,6.4,52,PG-13,44,107,2017,8.97
442,King Arthur: Legend of the Sword,King Arthur: Legend of the Sword,15371270,1713630,2017-05-12,3702,8371679,3585,2258,28098,"Charlie Hunnam, Astrid Bergès-Frisbey, Jude La...",Guy Ritchie,6.8,41,PG-13,30,126,2017,8.97
443,Jigsaw,Jigsaw,16640452,1855122,2017-10-27,2941,16582955,11614,5287,77518,"Matt Passmore, Tobin Bell, Callum Keith Rennie...","Michael Spierig, Peter Spierig",5.8,39,R,34,92,2017,8.97
444,American Assassin,American Assassin,14846778,1655159,2017-09-15,3154,2125097,400,245,5403,"Dylan O'Brien, Charlotte Vega, Christopher Bom...",Michael Cuesta,6.2,45,R,34,112,2017,8.97
445,The Foreigner,The Foreigner,13113024,1461875,2017-10-13,2515,9339280,8534,1430,78004,"Katie Leung, Jackie Chan, Rufus Jones, Mark Tandy",Martin Campbell,7.0,55,R,62,113,2017,8.97
446,"Everything, Everything","Everything, Everything",11727390,1307401,2017-05-19,2801,149335,169,26,1502,"Amandla Stenberg, Nick Robinson, Anika Noni Ro...",Stella Meghie,6.4,52,PG-13,46,96,2017,8.97
447,Wind River,Wind River,161558,18010,2017-08-04,4,3117558,898,409,5708,"Kelsey Asbille, Jeremy Renner, Julia Jones, Te...",Taylor Sheridan,7.8,73,R,87,107,2017,8.97
448,Geostorm,Geostorm,13707376,1528135,2017-10-20,3246,12582601,5467,5412,35397,"Gerard Butler, Jim Sturgess, Abbie Cornish, Al...",Dean Devlin,5.4,21,PG-13,13,109,2017,8.97
449,Fist Fight,Fist Fight,12201873,1360297,2017-02-17,3185,3848102,749,677,9289,"Charlie Day, Ice Cube, Tracy Morgan, Jillian Bell",Richie Keen,5.6,37,R,26,91,2017,8.97
450,How to be a Latin Lover,How to be a Latin Lover,12252439,1365935,2017-04-28,1118,4238676,301,202,2249,"Eugenio Derbez, Salma Hayek, Raphael Alejandro...",Ken Marino,5.9,54,PG-13,38,115,2017,8.97
451,Kidnap (2017),Kidnap,10016323,1116646,2017-08-04,2378,7567293,4033,1356,24320,"Halle Berry, Sage Correa, Chris McGinn, Lew Te...",Luis Prieto,5.9,44,R,37,95,2017,8.97
452,The Mountain Between Us,The Mountain Between Us,10551336,1176291,2017-10-06,3088,10822199,1404,936,12952,"Idris Elba, Kate Winslet, Beau Bridges, Dermot...",Hany Abu-Assad,6.4,48,PG-13,40,112,2017,8.97
453,Life (2017),Life,12501936,1393749,2017-03-24,3146,4204294,3080,784,13882,"Hiroyuki Sanada, Ryan Reynolds, Rebecca Fergus...",Daniel Espinosa,6.6,54,R,67,104,2017,8.97
454,"I, Tonya","I, Tonya",264155,29448,2017-12-08,4,59106,24,7,347,"Margot Robbie, Sebastian Stan, Allison Janney,...",Craig Gillespie,7.6,77,R,90,120,2017,8.97
455,Hostiles,Hostiles,22849,2547,2017-12-22,3,2316732,1530,491,7325,"Scott Shepherd, Rosamund Pike, Ava Cooper, Ste...",Scott Cooper,7.3,65,R,73,134,2017,8.97
456,Molly's Game,Molly's Game,2349967,261980,2017-12-25,271,6762396,1354,1342,12000,"Jessica Chastain, Idris Elba, Kevin Costner, M...",Aaron Sorkin,7.5,71,R,82,140,2017,8.97
457,The Nut Job 2: Nutty by Nature,The Nut Job 2: Nutty by Nature,8342311,930023,2017-08-11,4003,2975665,1057,992,12394,"Will Arnett, Maya Rudolph, Bobby Cannavale, Bo...",Cal Brunker,5.3,36,PG,13,91,2017,8.97
458,Rings,Rings,13002632,1449568,2017-02-03,2931,2278242,550,736,5839,"Matilda Anna Ingrid Lutz, Alex Roe, Johnny Gal...",F. Javier Gutiérrez,4.5,25,PG-13,7,102,2017,8.97
459,Logan Lucky,Logan Lucky,7600036,847272,2017-08-18,3031,10186232,2251,3609,26670,"Farrah Mackenzie, Channing Tatum, Jim O'Heir, ...",Steven Soderbergh,7.1,78,PG-13,93,118,2017,8.97
460,Home Again,Home Again,8567881,955170,2017-09-08,2940,4302200,277,294,1770,"Reese Witherspoon, Michael Sheen, Candice Berg...",Hallie Meyers-Shyer,5.7,41,PG-13,32,97,2017,8.97
461,The House,The House,8724795,972663,2017-06-30,3134,2556207,959,1308,13861,"Will Ferrell, Amy Poehler, Jason Mantzoukas, R...",Andrew Jay Cohen,5.6,30,R,18,88,2017,8.97
462,All the Money in the World,All the Money in the World,5584684,622595,2017-12-25,2074,4630096,1827,1873,14177,"Michelle Williams, Christopher Plummer, Mark W...",Ridley Scott,7.0,72,R,78,132,2017,8.97
463,Gifted,Gifted,446380,49763,2017-04-07,56,10490250,4681,1427,86404,"Chris Evans, Mckenna Grace, Lindsay Duncan, Oc...",Marc Webb,7.6,60,PG-13,73,101,2017,8.97
464,Downsizing,Downsizing,4954287,552317,2017-12-22,2668,9556537,4506,2126,25247,"Matt Damon, Christoph Waltz, Hong Chau, Kriste...",Alexander Payne,5.7,63,R,51,135,2017,8.97
465,The Bye Bye Man,The Bye Bye Man,13501349,1505167,2017-01-13,2220,5889726,2861,1419,9132,"Douglas Smith, Lucien Laviscount, Cressida Bon...",Stacy Title,4.3,37,PG-13,23,97,2017,8.97
466,Rough Night,Rough Night,8004283,892339,2017-06-16,3162,4949341,4913,13676,21178,"Scarlett Johansson, Jillian Bell, Zoë Kravitz,...",Lucia Aniello,5.2,51,R,45,101,2017,8.97
467,My Little Pony: The Movie,My Little Pony: The Movie,8885899,990624,2017-10-06,2528,4542819,8083,2998,34119,"Uzo Aduba, Ashleigh Ball, Adam Bengis, Emily B...",Jayson Thiessen,6.2,39,PG,47,99,2017,8.97
468,The Disaster Artist,The Disaster Artist,1211345,135044,2017-12-01,19,7279459,4993,1560,65876,"Dave Franco, James Franco, Seth Rogen, Ari Gra...",James Franco,7.6,76,R,91,104,2017,8.97

In [284]:
# Pickle merged dataframe
merged2.to_pickle("prelim_merged.pkl")